Show writing streak in stars. Addresses #4.

diff --git a/doily b/doily
--- a/doily
+++ b/doily
@@ -10,6 +10,7 @@ set -e
 # https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
 CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/doily"
 CONF_FILE="${CONF_DIR}/doily.cfg"
+DOILY_SRC="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
 
 
 if [[ -e "${CONF_FILE}" ]]; then
@@ -19,7 +20,7 @@ else
     # This bit of magic is determining the directory where the script being
     # executed is located, across symlinks, to get to the example config.
     # Based on: http://unix.stackexchange.com/a/17500
-    cp "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/default.cfg" "${CONF_FILE}"
+    cp "${DOILY_SRC}/default.cfg" "${CONF_FILE}"
     cat <<EOF
 Configuration file created in: ${CONF_FILE}
 
@@ -82,9 +83,18 @@ if [[ -n "${use_git}" ]]; then
     # on, though, it ensures the repo gets created and old dailies are included.
     git -C "${doily_dir}" init
     git -C "${doily_dir}" add .
+    # The commit commands will return non-zero if we didn't commit anything,
+    # but that's okay, so add an extra true to keep set -e from exiting.
     if [[ -n "${auto_commit}" ]]; then
-        git -C "${doily_dir}" commit -m "Automatic commit from Doily."
+        git -C "${doily_dir}" commit -m "Automatic commit from Doily." || true
     else
-        git -C "${doily_dir}" commit
+        git -C "${doily_dir}" commit || true
     fi
+fi
+
+
+if [[ -n "${show_streak}" ]]; then
+    echo
+    source "${DOILY_SRC}/show_streak.sh"
+    echo "$(doily::get_streak)"
 fi
